# This is a basic workflow to help you get started with Actions

name: release

on:
  pull_request:
    branches: master

jobs:
  append_changelog:
    if: startsWith(github.event.comment.body, '/version')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          version = github.event.comment.body.split()[1]
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 That works! Generating preview for' + version 
          });
